### DISCUSSION TITLE
Use ASR Adapters with Citrinet model

### DISCUSSION THREAD

**Discussion by manuel3265** [NVIDIA-NeMo/NeMo#4334] [General]
Hello, is there someone who can help me use the adapters with models other than the conformer ones. I want to use the adapters with the citrinet models and would like to know if it is possible and how I could do it.

**Comment by titu1994** [comment]
Citrinet is compatible with adapters and followed the same steps. You may need to modify the optimization hyper parameters slightly but it should still work. 

Can you explain in detail what you tried and what was the result.

**Reply by manuel3265** [reply]
@titu1994 Too bad for you, the Adapters training functionality works but it doesn't generate good results. This is the quick implementation I did.

[Citrinet_with_adapters](https://colab.research.google.com/drive/1UKVo0t6Qmhq2iqXO7uQ60gl0SwmhCnr8?usp=sharing)

Sorry if it's a bit messy, but it shows the results of the model returning a wer of 1.0 after training.

Thanks

**Reply by titu1994** [reply]
```
optim:
  name: novograd
  lr: 0.05
  betas:
  - 0.8
  - 0.25
  weight_decay: 0.001
  sched:
    name: CosineAnnealing
    warmup_steps: 1000
    warmup_ratio: null
    min_lr: 1.0e-05
    last_epoch: -1
```

As I said, optimization parameters need to be changed. The base LR for Novograd is 0.05, your notebook sets it as 0.1, which I higher than when even training with Global Batch Size of 1024 of more. 

I would advise using much lower LR, and preferable switch to Adam for adapter optimization. It's usually much less to tune that way. 

Basically set optim.name=adamw, betas=(0.9, 0.98), and LR=0.001. For Adam based optimizer, modify LR is sufficient.
