### DISCUSSION TITLE
Loading a custom vocabulary for a pre-trained model

### DISCUSSION THREAD

**Discussion by stefanhgm** [NVIDIA-NeMo/NeMo#4688] [Q&A]
Hi everyone,

I have a pre-trained model provided in a .nemo container which contains:
```
mp_rank_00/model_weights.ckpt
mp_rank_01/model_weights.ckpt
model_config_fixed.yaml
```

I now have separate `vocab.json`,` merges.txt`, and `special_tokens_map.json` files that I want to inject into the model, but unfortunately without success so far!

I use the `nvcr.io/nvidia/nemo:22.05` container as environment and load the model with `NeMo/examples/nl-language_modeling/megatron_gpt_eval.py` via (I set pipeline_model_parallel_size to 2 due to the two ranks in the model):

```
python megatron_gpt_eval.py s gpt_model_file=PATH_TO_MODEL.nemo  trainer.devices=2  trainer.num_nodes=1 tensor_model_parallel_size=1 pipeline_model_parallel_size=2 server=True
[...]
Getting HuggingFace AutoTokenizer with pretrained_model_name: gpt2, vocab_file: /root/.cache/torch/megatron/megatron-gpt-345m_vocab, merges_files: /root/.cache/torch/megatron/megatron-gpt-345m_merges, special_tokens_dict: {}, and use_fast: False
[...]
```

So, it seems that a default tokenizer with a default vocabulary is loaded, which obviously generates only garbage.

Now I want to inject my custom `vocab.json`,` merges.txt`, and `special_tokens_map.json` files, but this does not work.

I tried two things:

1. I added the `vocab.json`,` merges.txt` to a new model_config_fixed.yaml and modified the model loading routine in `megatron_gpt_eval.py` to
`model = MegatronGPTModel.restore_from(restore_path=cfg.gpt_model_file, override_config_path="/workspace/nemo/ibc/NeMo/models/model_config_fixed.yaml", trainer=trainer)`

2. I unpacked the .nemo file and changed the config appropriately for my custom `vocab.json`,` merges.txt`  files.

In both cases the loading shows the correct `vocab.json`,` merges.txt` files:
```
python megatron_gpt_eval.py s gpt_model_file=PATH_TO_MODEL.nemo  trainer.devices=2  trainer.num_nodes=1 tensor_model_parallel_size=1 pipeline_model_parallel_size=2 server=True
[...]
You tried to register an artifact under config key=tokenizer.vocab_file but an artifact for it has already been registered.
Getting Megatron tokenizer for pretrained model name: megatron-gpt-345m, custom vocab file: /PATH-TO-CORRECT-VOCAB/vocab.json, and merges file: /PATH-TO-CORRECT-VOCAB/merges.txt
Getting HuggingFace AutoTokenizer with pretrained_model_name: gpt2, vocab_file: /PATH-TO-CORRECT-VOCAB/vocab.json, merges_files: /PATH-TO-CORRECT-VOCAB/merges.txt, special_tokens_dict: {}, and use_fast: False
[...]
```

However, the model still produces wrong outputs and I think this might either be due to incorrect loading of the vocabulary or the missing `special_tokens_map.json` that I failed to load so far.

So my questions would be:

1) How to inject the `special_tokens_map.json` I failed to do so with both approaches?
2) Is there an easier way to inject the custom `vocab.json`,` merges.txt`, and `special_tokens_map.json` files? E.g., via CLI? It seems like the CLI arguments do not influence the model configuration.
3) Is it necessary to add the `vocab.json`,` merges.txt`, and `special_tokens_map.json` files to the nemo container to load them properly?

model_config_fixed.yaml:
```
micro_batch_size: 4
global_batch_size: 8
tensor_model_parallel_size: 2
pipeline_model_parallel_size: 1
resume_from_checkpoint: null
encoder_seq_length: 2048
max_position_embeddings: 2048
num_layers: 24
hidden_size: 4096
ffn_hidden_size: 16384
num_attention_heads: 32
init_method_std: 0.02
hidden_dropout: 0.1
kv_channels: null
apply_query_key_layer_scaling: true
layernorm_epsilon: 1.0e-05
make_vocab_size_divisible_by: 128
pre_process: true
post_process: true
persist_layer_norm: true
grad_div_ar_fusion: true
tokenizer:
  library: megatron
  type: GPT2BPETokenizer
  model: null
  vocab_file: /PATH-TO-WRONG-VOCAB/gpt3-357m/vocab.json
  merge_file: /PATH-TO-WRONG-VOCAB/gpt3-357m/merges.txt
  delimiter: null
native_amp_init_scale: 4294967296
native_amp_growth_interval: 1000
hysteresis: 2
fp32_residual_connection: false
fp16_lm_cross_entropy: false
megatron_amp_O2: false
grad_allreduce_chunk_size_mb: 125
seed: 1234
use_cpu_initialization: false
onnx_safe: false
apex_transformer_log_level: 30
gradient_as_bucket_view: true
activations_checkpoint_method: null
activations_checkpoint_num_layers: 1
data:
  [...]
optim:
  [...]
```
