### DISCUSSION TITLE
Optimizing Cache Aware Conformer w/ Riva Configs

### DISCUSSION THREAD

**Discussion by piraka9011** [NVIDIA-NeMo/NeMo#5284] [Q&A]
First of all, appreciate all the work being put into the new Conformer models. Lots of exciting progress!

We're fine-tuning new conformer models on our dataset and were wondering whether the parameters we specify during training should reflect the expected `riva-build` configuration?

If they should, consider the default streaming conformer config provide [here](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/streaming/conformer_ctc_bpe_streaming.yaml)
* `n_layers`: 18
* `downsampling`: 4x
* `window_stride` (`window_shift`, ms): 10

Would the corresponding Riva build config be:
* `chunk_size` (ms): 40
* `padding_size` (ms, left and right context): `n_layers` * 2 * `downsampling` * `window_stride` = 1440

Unsure if we should multiply the above equation by 2 since the docs say there's "2 right context in each layer" but not sure if that's referring to the left/right context or that you feed 2 contexts/chunks to the model each time.

Does the NeMo version also affect which Riva version we should use btw for conformers, since it seems FP16 support is unstable/sometimes results in NaN loss?

**Comment by titu1994** [comment]
Riva does not support chunk aware Conformer as of now. It is planned to add support for it in the coming months. Since this is a very different model and way to do inference it will take a few months or so to get it into Riva.

**Reply by msis** [reply]
Has there been any progress on this?
Is there a relation ship between these lines in the `encoder` and the settings about paddings (left/right) in RIVA?
```yaml
    # [left, right] specifies the number of steps to be seen from left and right of each step in self-attention
    # for att_context_style=regular, the right context is recommended to be a small number around 0 to 3 as multiple-layers may increase the effective right context too large
    # for att_context_style=chunked_limited, the left context need to be dividable by the right context plus one
    att_context_size: [102, 33] # -1 means unlimited context
    att_context_style: chunked_limited # regular or chunked_limited
```
