### DISCUSSION TITLE
Is NeMo Speaker Diarization deterministic for a given audio file?

### DISCUSSION THREAD

**Discussion by filmo** [NVIDIA-NeMo/NeMo#7170] [General]
Given a particular audio files are the results from NeuralDiarizer() deterministic or is there a probabilistic element to the process that will vary slightly from run to run?

**Comment by naymaraq** [comment]
In clustering stage NeMo uses K-means clustering algorithm, which contain random elements.
https://github.com/NVIDIA/NeMo/blob/2cc09425aba3e9b3cfdba43a3188eaef58227055/nemo/collections/asr/parts/utils/offline_clustering.py#L715

Although it set random state, but on different machines it might produce different results for a given audio file

**Reply by filmo** [reply]
Thanks for pointer to the documentation:

```
Perform k-means clustering on spectral embeddings. To alleviate the effect of randomness,
k-means clustering is performed for (self.n_random_trials) times then the final labels are obtained
by taking a majority vote. If speed is the major concern, self.n_random_trials should be set to 1.
n_random_trials=30 is recommended to see an improved result.
```
It seems like SpectralClustering() defaults to n_random_trials = 1

Using NeuralDiarizer() from mo.collections.asr.models.msdd_models I couldn't figure out how to set this parameter.  NeuralDiarizer() calls ClusterEmbedding() but I couldn't find a reference to SpectralClustering(), (which is probably my fault for not being able to follow the entire flow path of the library.)

In any case, how would I set `n_random_trials` to some value other than n=1 ?

I'm initializing NeuralDiarizer() using diar_infer_telephonic.yaml as the base config file.  Is it simply setting an additional parameter in the section:

```
  clustering:
    parameters:
      oracle_num_speakers: False # If True, use num of speakers value provided in manifest file.
      max_num_speakers: 8 # Max number of speakers for each recording. If an oracle number of speakers is passed, this value is ignored.
      enhanced_count_thres: 80 # If the number of segments is lower than this number, enhanced speaker counting is activated.
      max_rp_threshold: 0.25 # Determines the range of p-value search: 0 < p <= max_rp_threshold. 
      sparse_search_volume: 30 # The higher the number, the more values will be examined with more time. 
      maj_vote_spk_count: False  # If True, take a majority vote on multiple p-values to estimate the number of speakers.
```

Thank you in advance for your help.
