### DISCUSSION TITLE
Does the augmentor work in the training step as well as the validation step?

### DISCUSSION THREAD

**Discussion by june-oh** [NVIDIA-NeMo/NeMo#7847] [General]
I want to apply noise augmentation to the validation step to train a noise-robust model. 

I understand that SpecAug does not apply to the validation step. 

Does it work when explicitly specifying an augmenter, such as a white noise augmenter?

I am using fastconformer.

Here is a part of the yaml file 

```yaml
model:
  ...
  train_ds:
  ...
      augmentor:
          white_noise:
              prob: 0.5
              min_level: -50
              max_level: -10
   ...
   validation_ds:
  ...
      augmentor:
          white_noise:
              prob: 1.0
              min_level: -50
              max_level: -10

          
```

If set up as above, noise should be mixed in the validation step and a drop in WER (compared to w/o noise augmentation).

However, when comparing val_wer to training without augmentation, it seems that no noise augmentation is being applied.
